create table projects
(
    id          integer generated by default as identity
        primary key,
    created_at  date,
    description varchar(255),
    edited_at   date,
    name        varchar(255)
);

alter table projects
    owner to chantreck;

create table users
(
    id         integer generated by default as identity
        primary key,
    created_at date,
    edited_at  date,
    login      varchar(255),
    name       varchar(255),
    password   varchar(255),
    role       varchar(255)
);

insert into users
(created_at, edited_at, login, name, password, role)
VALUES ('0001-01-01', '0001-01-01', 'Root', 'root', 'root', 'ADMIN');

alter table users
    owner to chantreck;

create table comments
(
    id         integer generated by default as identity
        primary key,
    created_at date,
    edited_at  date,
    text       varchar(255),
    user_id    integer
        constraint comments_user_fk
            references users
);

alter table comments
    owner to chantreck;

create table tasks
(
    id           integer generated by default as identity
        primary key,
    created_at   date,
    description  varchar(255),
    edited_at    date,
    priority     varchar(255),
    tasketa      integer,
    title        varchar(255),
    creator_id   integer
        constraint tasks_creator_fk
            references users,
    performer_id integer
        constraint tasks_performer_fk
            references users,
    project_id   integer
        constraint tasks_project_fk
            references projects
);

alter table tasks
    owner to chantreck;

create table task_comment
(
    comment_id integer not null
        constraint task_comment_comment_fk
            references comments,
    task_id    integer not null
        constraint task_comment_task_fk
            references tasks
);

alter table task_comment
    owner to chantreck;

